export APPD_MACHINE_AGENT_ZIP_FILE="machineagent-bundle-64bit-linux-4.5.18.2430.zip"
export APPD_MAC_AGENT_HOST="localhost"
export APPD_MAC_AGENT_PORT="8081"
export APPD_MAC_AGENT_PATH="/api/v1/metrics"
export APPD_MACHINE_AGENT_OPTIONS=" -Dmetric.http.listener=true -Dmetric.http.listener.port=8081 "
